### ISSUE TITLE
Bot Keeps Displaying Error when users send a message

### ISSUE THREAD

**Issue by yabberish** [Darkempire78/Mee6-Bypasser#4]
![image](https://user-images.githubusercontent.com/49889930/99123462-3eadcb80-25ce-11eb-8ddf-ad3a9f7ede51.png)
The bot keeps displaying this error, I didn't change anything in the code other then the bot token.

**Comment by clementwzk** [comment]
Hi, 
If we write the url, we can see that it running.
![image](https://user-images.githubusercontent.com/50015928/99145199-132dee00-266d-11eb-96cd-15a6675d7145.png)
So, we can suppose that the error is caused by request spam.

I think that i will change the system to do a request only when the user use the !rank command (and add only when the user do the command). But we can also add a cooldown 🤔

**Comment by yabberish** [comment]
> Hi,
> If we write the url, we can see that it running.
> ![image](https://user-images.githubusercontent.com/50015928/99145199-132dee00-266d-11eb-96cd-15a6675d7145.png)
> So, we can suppose that the error is caused by request spam.
> 
> I think that i will change the system to do a request only when the user use the !rank command (and add only when the user do the command). But we can also add a cooldown 🤔

Alright, could you notify me when you change it?

**Comment by clementwzk** [comment]
Yes i will try not to forget, but the better way is to star the repository

**Comment by yabberish** [comment]
Is it fixed yet?

**Comment by clementwzk** [comment]
New system was released!
Use the task sytem if your server sends a lot of messages
